### ISSUE TITLE
build error about std::span

### ISSUE THREAD

**Issue by genkiiii** [djarek/canary#18]
Build error occurred and the compiler said no span in std.

target_compile_features is set to c11 in the original CMakeLists.txt.
I think c20 is needed for span.

**Comment by djarek** [comment]
Ah, yes it should've been `>` rather than `>=` here: https://github.com/djarek/canary/blob/164db1268a88af5c822f11c131e3c5798f7928bd/include/canary/detail/config.hpp#L27
